<a href="https://colab.research.google.com/github/samapatil1729/Business-Analytics/blob/main/MLT_week_5_to_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**WEEK_5**

##Practice Programing Question 1
Define a function `cross_entropy(y,sigmoid_vector,w,reg_type,reg_rate) `
having the 
following characteristics: 

Input:

`y`: Actual output label vector

`sigmoid_vector`: logistic value of predicted output 

`w`: weight vector

`reg_type`: type of regularization as string, either 'l1' 
or 'l2'. Default 'l2'.

`reg_rate`: regularization rate. Default value 0.

`Output:`

Binary cross entropy loss(float value)

In [ ]:
import numpy as np
def cross_entropy(y,sigmoid_vector,w, reg_type,reg_rate):
    y_hat = sigmoid_vector
    base_loss = -np.sum(y*np.log(y_hat)+(1-y)*np.log(1-y_hat))
    if reg_type == 'l1':
        penalty = (reg_rate/2)*np.sum(np.abs(w))
    else:
        penalty = (reg_rate/2)*np.sum(w*w)
    loss = base_loss + penalty
    return loss

##Practice Programing Question 2
Write a function sigmoid(X) which returns logistic function of X, where X is a numpy array.

Input: A numpy array X.

Output: Logistic function of X.

In [ ]:
import numpy as np
def sigmoid(X):
  sig = 1/(1+np.exp(-X))
  return sig

##Graded Programing Question 1

Assume that we have trained a logistic regression classifier on a dataset and have learned the weight `w`. Define a function `predict_label(X,w)` which accepts a feature matrix `X` of test samples and the weight vector `w` as arguments, and assigns labels to each of the samples based on the following conditions:

If the model's output is greater than or equal to 0.75, assign the predicted label as 1

If the model's output is less than or equal to 0.25, assign the predicted label as -1

Otherwise, assign the label as 0

The function should return the vector of predicted labels. Use the `sigmoid` activation function while calculating the model's output for all the sample values in the test-set.

In [ ]:
import numpy as np
def predict_label(X,w):
    z = X@w
    sig = 1 / (1+np.exp(-z))
    labels = (sig >= 0.25).astype(int)
    return labels

OR

In [ ]:
import numpy as np
def predict_label(x,w):  
  y_hat = 1/(1+np.exp(-(x @ w)))
  labels=[]
  # compute label of the sample
  for y in y_hat:
    if y<=0.25:
      label=-1
    elif y>=0.75:
      label=1
    else:
      label=0
    labels.append(label)
  return np.array(labels)

##Graded Programing Question 2

Define a function `gradient(X, y, w, reg_rate)` which can be used for optimization of `logistic regression model` with `L2` regularization having the following characteristics:

`Input:`

X: Feature matrix for training data.

y: Label vector for training data.

reg_rate: regularization rate

w: weight_vector

Output:

A vector of gradients.

In [ ]:
import numpy as np
def gradient(X,y,w,reg_rate):
    z = X@w
    y_hat = 1 / (1+np.exp(-z))
    G = np.transpose(X) @ (y_hat-y) + reg_rate * w
    return G

##Graded Programing Question 3
Define a function `update_w(X, y, w, reg_rate, lr)` which can be used for optimization of logistic regression model with L2 regularization having following characteristics:

`Input:`

`X`: Feature matrix for training data.

`y`: Label vector for training data.

`reg_rate`: regularization rate

`w`: weight_vector

`lr`: learning rate

`Output`:

A vector of updated weights.

You need to perform exactly one update over the entire data.

In [ ]:
import numpy as np
def update_w(X, y, w, reg_rate, lr):
    z = X@w
    sig = 1 / (1+np.exp(-z))
    G = np.transpose(X) @ (sig - y) + reg_rate * w
    U = w - lr*G
    return U

#**WEEK_6**

##Practice Programing Question 1



Write a function named `bernoulli_naive_bayes` that accepts a feature matrix `X` and a label vector `y` as arguments. 

It should return the parameter matrix P. Both the arguments and the return value are of type np.ndarray. You can assume that no smoothing is required.

In [ ]:
import numpy as np
def bernoulli_naive_bayes(X, y):
    """
    Estimate the parameter matrix
    
    Arguments:
    	X: feature matrix, (100, 2), np.ndarray
    	y: label vector, (100, ), np.ndarray
    Return:
    	P: parameter matrix, (2, 2), np.ndarray
    """
    a,b = X.shape
    classes = np.unique(y)
    n = len(classes)
    w = np.zeros((b,n), dtype = np.float64)
    for i, c in enumerate(classes):
        x_c = X[y == c]
        w[i,:] = np.sum(x_c, axis = 0)/x_c.shape[0]
    return w.T

In [ ]:
X = np.array([[1,0],[0,1],[0,1],[1,0]])
y = np.array([1,0,0,1])
bernoulli_naive_bayes(X, y)

array([[0., 1.],
       [1., 0.]])

##Practice Programing Question 2

You are given a numerical data matrix `x` as an `np.ndarray (shape 200 \times 5200×5)` and a vector of class labels y `(size 200)` as np.ndarray for a multi-class classification problem. 

Define a function `mean_estimate` which calculates the `estimated mean` of data samples corresponding to the class labels for each feature and returns a dictionary with class labels as keys and estimated mean vectors as values. The i^{th}i 
th
  element of a mean vector corresponds to the i^{th}i 
th
  feature.


In [ ]:
import numpy as np
def mean_estimate(X: np.ndarray,  y : np.ndarray):
    """
    Estimate the mean of samples for each class

    Arguments:
        X: samples, (200, 5), np.ndarray
        y: labels, (200, ), np.ndarray
    Return:
        D: dictionary
            key: label, int
            value: mean, np.ndarray
    """
    a,b = X.shape
    classes = np.unique(y)
    d = {}
    for c in classes:
        x_c = X[y == c]
        d[c] = np.mean(x_c, axis = 0)
    return d

##Practice Programing Question 3
Write a function `naive_gaussian_predict` that implements a `Gaussian Naive Bayes` model on training data, and returns the predicted class labels for the test data. 

This is a binary classification task `(labels are 0 and 1)` and the size of `X_train, y_train` and `X_test` are fixed to 

(800×2), (800, ) and (200×2) respectively. The function signature is as follows:

    Arguments:
        X_train: train samples, (800, 2), np.ndarray 
        y_train: train labels,  (800, ), np.ndarray 
        X_test:  test samples, (200, 2), np.ndarray
    Return  
        y_pred: test labels, (200, ) np.ndarray

In [ ]:
import numpy as np
def fit(X,y):
    n_samples, n_features= X.shape
    classes= np.unique(y)
    n_classes= len(classes)
    mean= np.zeros((n_classes, n_features), dtype= np.float64)
    var= np.zeros((n_classes, n_features), dtype= np.float64)
    priors= np.zeros(n_classes, dtype= np.float64)
    for i, c in enumerate(classes):
        X_c= X[y==c]
        mean[i,:]= X_c.mean(axis=0)
        var[i,:]= X_c.var(axis=0)
        priors[i]= X_c.shape[0]/float(n_samples)
    return (mean, var, priors, classes)
def calc_pdf(class_id, X,mean,var):
    mean= mean[class_id]
    var= np.diag(var[class_id])
    z= np.power(2* np.pi,X.shape[0]/2) *np.power(np.linalg.det(var),1/2)
    return (1/z)* np.exp(-(1/2)*(X-mean).T @(np.linalg.inv(var))@(X-mean))
def calc_prod_likelihood_prior(X, classes, priors, mean, var):
    prod_likelihood_prior= np.zeros((X.shape[0], len(classes)), dtype= np.float64)
    for x_i, x in enumerate(X):
        for i, c in enumerate(classes):
            prod_likelihood_prior[x_i,c]= (np.log(calc_pdf(i,x, mean, var))+ np.log(priors[i]))
    return prod_likelihood_prior
def naive_gaussian_predict(X_train, y_train, X_test):
    mean, var, priors, classes= fit(X_train,y_train)
    likelihood_prior= calc_prod_likelihood_prior(X_test, classes, priors, mean, var)
    return np.argmax(likelihood_prior, axis=1)
    """
    Train a Gaussian NB and predict the labels on test set 

    Arguments:
        X_train: train samples, (800, 2), np.ndarray 
        y_train: train labels,  (800, ), np.ndarray 
        X_test:  test samples, (200, 2), np.ndarray
    Return  
        y_pred: test labels, (200, ) np.ndarray
    """

##Practice Programing Question 4

For a binary classification problem with class labels (0 and 1), define a function `class_scores` that accepts the true and predicted labels and returns the following evaluation metrics as a dictionary.

`(1) Precision`

`(2) Recall`

`(3) Accuracy`

`(4) F1 score`

`(5) Misclassification Rate`

They keys of the dictionary are the names of the metrics, exactly as they are given above. The values are the corresponding measurements expressed as floats. The function should have the following signature:
Arguments:  

    y_test: true labels, (n, ), np.ndarray 
    y_pred: predicted labels, (n, ), np.ndarray
Return:

    metrics: dictionary
        key: string, names of the metrics
        value: float

Both numpy arrays are of size (n, ). Do not use any existing methods/functions to calculate the same. Consider label 1 as the positive class. Note that the misclassification rate is 1 minus the accuracy.

In [ ]:
import numpy as np
def class_scores(y_test: np.ndarray, y_pred: np.ndarray):
    """
    Compute evaluation metrics for a binary classification task
    
    Arguments:  
        y_test: true labels, (n, ), np.ndarray 
        y_pred: predicted labels, (n, ), np.ndarray
    Return:
        metrics: dictionary
            key: string, names of the metrics
            value: float
    """
    TP = 0
    TN = 0
    FP = 0
    FN = 0
    for i in range(len(y_test)):
        if y_test[i] == 1 and y_pred[i] == 1:
            TP+=1
        elif y_test[i] == 0 and y_pred[i] == 0:
            TN+=1
        elif y_test[i] == 1 and y_pred[i] == 0:
            FN+=1
        else:
            FP+=1
            
    P = TP/(TP+FP)
    R = TP/(TP+FN)
    A = (TP+TN)/(TP+TN+FN+FP)
    f1 = (2*P*R)/(P+R)
    MCR = (FN+FP)/(TP+TN+FN+FP)
    
    d = {'Precision':P, "Recall":R, 'Accuracy':A, 'F1_score':f1, 'Misclassification_rate':MCR}
    return d

##Graded Programing Question 1
In a multi-class classification setting, consider a numerical feature matrix `X` as an np.ndarray of shape (n, m) and a vector of class labels `y` of size (n, ) as an np.ndarray. 

Define a function `variance_estimate` which calculates the estimated variance of data samples corresponding to individual class labels for each feature. The function should return a dictionary with class labels as keys and estimated variance vectors as values. The i^{th} element of a vector corresponds to the variance of the i^{th} feature.

In [ ]:
import numpy as np
def variance_estimate(X: np.ndarray, y: np.ndarray):
    
    """
    Estimate the variance of samples for each class

    Arguments:
        X: feature matrix, (n, m), np.ndarray
        y: label vector, (n, ), np.ndarray
    Return:
        D: dictionary
           key: label, int
           value: variance, (m, ), np.ndarray
    """
    class_count = np.unique(y)
    class_dic = {}
    for c in (class_count):
        X_c = X[y==c]
        class_dic[c] = X_c.var(axis = 0)
    return class_dic

OR

In [ ]:
import numpy as np
def variance_estimate(X: np.ndarray,  y: np.ndarray):
    D = {}
    labels = np.unique(y)
    for label in labels:
        D[label] = np.var(X[y == label], axis = 0)
    return D

##Graded Programing Question 2
Write a function `naive_gmodel_eval` that implements a Gaussian Naive Bayes model on training data, predicts class labels for the test data and returns the evaluation scores for the predictions performed on the test data, corresponding to `each individual label `appearing on `y_test`. 

This is a multiclass classification task and the size of `X_train, y_train, X_test and y_test` are fixed to (1800, 5), (1800,), (200,5) and (200,) respectively. There are four classes labeled as 0, 1, 2, 3


---
For each label, the following evaluation metrics have to be generated by treating that label as a positive class and all others as the negative class.

(1) Precision

(2) Recall

(3) Accuracy

(4) F1 score

(5) Misclassification Rate

This information has to be stored in a dictionary. They keys of the dictionary are the names of the metrics, exactly as they are given above. The values are the corresponding measurements expressed as floats.


---
Create a parent dictionary named `metrics`. The keys of this dictionary will be the labels and the values will be the corresponding evaluation dictionaries. So, your function should return `metrics`, which is essentially a dictionary of dictionaries!


---
The function will have the following signature:

    Arguments:
        X_train: training samples, (1800, 5), np.ndarray
        y_train: training labels, (1800, ), np.ndarray, labels are 0, 1, 2 or 3
        X_test:  test samples, (200, 5), np.ndarray
        y_test:  test_labels, (200, ), np.ndarray, labels are 0, 1, 2, or 3
    Return:
        metrics: dict of dicts
           key: label, int
           value: dict
               key: string
               value: float



In [ ]:
import numpy as np
def class_scores(y_test, y_pred, positive):
    tp = np.sum((y_test == positive) & (y_pred == positive))
    tn = np.sum((y_test != positive) & (y_pred != positive))
    fp = np.sum((y_test != positive) & (y_pred == positive))
    fn = np.sum((y_test == positive) & (y_pred != positive))

    names = ("Precision", "Recall","Accuracy", "Misclassification Rate","F1 score")
    values = [tp / (tp + fp), tp / (tp + fn), (tp + tn) / (tp + tn + fp + fn)]
    values.append(1 - values[-1])
    values.append(2 * values[0] * values[1] / (values[0] + values[1]))

    scores = dict(zip(names,values))
    return scores

# Solution
class NB(object):

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self._classes = np.unique(y)
        n_classes = len(self._classes)

        # calculate mean, var, and prior for each class
        self._mean = np.zeros((n_classes, n_features), dtype = np.float64)
        self._var = np.zeros((n_classes, n_features), dtype = np.float64)
        self._priors = np.zeros(n_classes, dtype = np.float64)

        for c in self._classes:
            X_c = X[y == c]
            self._mean[c, :] = X_c.mean(axis = 0)
            self._var[c, :] = X_c.var(axis = 0)
            self._priors[c] = X_c.shape[0] / float(n_samples)

    def predict(self, X):
        self._posterior = np.zeros((X.shape[0], len(self._classes)), dtype = np.float64)
        for idx, x in enumerate(X):
            for c in self._classes:
                self._posterior[idx, c] = np.log(self._pdf(c, x)) + np.log(self._priors[c])
        return np.argmax(self._posterior, axis = 1)

    def _pdf(self, class_idx, X):
        mean = self._mean[class_idx]
        var = np.diag(self._var[class_idx])
        z = np.power(2 * np.pi, X.shape[0]/2) * np.power(np.linalg.det(var), 1/2)
        return (1 / z) * np.exp(-(1 / 2) * (X - mean).T @ (np.linalg.inv(var)) @ (X - mean))

def naive_gmodel_eval(X_train, y_train, X_test, y_test):
    gaussian_nb = NB()
    gaussian_nb.fit(X_train, y_train)
    y_pred = gaussian_nb.predict(X_test)

    labels = np.unique(y_train)
    D = {}
    for label in labels:
        D[label] = class_scores(y_test, y_pred, label)
    return D

#**WEEK_7**

##Practice Programing Question 1
Write a function `euclid(a,b)` to find `Euclidean distance` between vectors a and b. Both a and b have shape (n,1), where n is number of features/dimensions.

Input: Vectors a and b

Output: Euclidean distance between vectors a and b

In [ ]:
import numpy as np
def euclid(a,b):
  E = np.sum((a-b)**2,axis=1)
  return E

##Practice Programing Question 2

Write a function `one_hot(y)` which performs `one hot encoding` on vector y and then outputs a resultant matrix which can be used for softmax regression as output label matrix. y is row matrix with (n,1) shape, where n is number of samples.

Example: if y is `[8, 6, 3]`, its one hot encoding will be
 [[0, 0, 1],[0, 1, 0],[1, 0, 0]].

Input: y: A vector of shape (n,1)

Output: A output label matrix of suitable shape.

In [ ]:
import numpy as np
def one_hot(y):
    label_list = list(np.unique(y))
    M = np.zeros((len(y),len(label_list)))
    for i in range(len(y)):
        M[i,label_list.index(y[i])] = 1       # M[i][label_list.index(y[i])] = 1
    return M

In [ ]:
y = [8, 6, 3]

In [ ]:
one_hot(y)

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
one_hot(y)

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
np.unique(y)

array([3, 6, 8])

##Graded Programing Question 1

Write a function `manhattan(a,b)` to find `Manhattan distance` between vectors a and b. Both a and b are vectors with shape (n,1) where n is number of features/dimensions.

Input: Vectors a and b

Output: Manhattan distance between vectors a and b

In [ ]:
import numpy as np
def manhattan(a,b):
  dist = np.sum(np.abs(a-b))
  return dist

In [ ]:
x = np.array([1, 2, 3])
y = np.array([8, 6, 3])

manhattan(x,y)

11

##Graded Programing Question 2
Write a `function softmax(Z)` to find softmax of linear combination of feature matrix and weight vector.

Take care of numerical stability as well.

`Input`: Z = X@W, where X is feature matrix of shape (n,m), W is weight matrix (m,k),

 where n = number of rows, m = number of features and k = number of labels.

`Output`: A matrix of (n,1) shape. Each row corresponds to the label of that row. 

Each label will have value from 0 to k-1.


In [ ]:
import numpy as np
def softmax(Z):
  exp = np.exp(Z-np.max(Z))
  for i in range (len(Z)):
      exp[i] /= np.sum(exp[i])
  return exp

In [ ]:
Z = [3.0, 1.0, 0.2]
print(softmax(Z))

[1. 1. 1.]


In [ ]:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [ ]:
Z = [3.0, 1.0, 0.2]
print(softmax(Z))

[0.8360188  0.11314284 0.05083836]


##Graded Programing Question 3
Write a function `knn(class1, class2, x_new)` to find in which cluster x_new belongs using 3-NN. Assume cluster 1 and cluster 2 has 5 points each. Use Euclidian distance as distance measure.

`Input: `

Two numpy arrays class1 and class2 of shape (5,2) each and a numpy array x_new of shape (2,1)

`Output:`

 Return class id to which x_new belongs (i.e. 1 or 2) .

In [ ]:
import numpy as np
def knn(class1,class2,x_new):
  dist1 = np.sum((np.transpose(x_new)-class1)**2,axis=1)  
  dist2 = np.sum((np.transpose(x_new)-class2)**2,axis=1)
  dist1 = np.append([dist1],np.ones((1,5)),axis=0)
  dist2 = np.append([dist2],2*np.ones((1,5)),axis=0)
  dist  = np.concatenate((dist1, dist2), axis=1)
  #ii = np.argsort(dist[0])
  dist  = np.sort(dist, axis=1)
  #dist = dist[:,ii]
  if np.sum(dist[1][0:3])<=4:
    return 1
  else:
    return 2

In [ ]:
class1 = np.array([[1,1], [1,2], [2,3], [1,5], [3, 2]])
class2 = np.array([[-1,-1],[-1,-2],[-2,--3], [-1,-5], [-3,-2]])
class1.shape, class2.shape

((5, 2), (5, 2))

In [ ]:
x_new = np.array([[2], [3]])
x_new.shape

(2, 1)

In [ ]:
x_new.T - class1

array([[ 1,  2],
       [ 1,  1],
       [ 0,  0],
       [ 1, -2],
       [-1,  1]])

In [ ]:
 dist1 = np.sum((np.transpose(x_new)-class1)**2,axis=1) 
 print(dist1)
 dist1 = np.append([dist1],np.ones((1,5)),axis=0)
 dist1

[5 2 0 5 2]


array([[5., 2., 0., 5., 2.],
       [1., 1., 1., 1., 1.]])

In [ ]:
dist2 = np.sum((np.transpose(x_new)-class2)**2,axis=1)
print(dist2)
dist2 = np.append([dist2],2*np.ones((1,5)),axis=0)
dist2

[25 34 16 73 50]


array([[25., 34., 16., 73., 50.],
       [ 2.,  2.,  2.,  2.,  2.]])

In [ ]:
dist  = np.concatenate((dist1, dist2), axis=1)
dist

array([[ 5.,  2.,  0.,  5.,  2., 25., 34., 16., 73., 50.],
       [ 1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.]])

In [ ]:
dist  = np.sort(dist, axis=1)
dist

array([[ 0.,  2.,  2.,  5.,  5., 16., 25., 34., 50., 73.],
       [ 1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.]])

In [ ]:
np.sum(dist[1][0:3])

3.0

In [ ]:
knn(class1,class2,x_new)

1

#**WEEK_8**

##Practice Programing Question 1
Write a function named `"hinge_loss"` that computes the hinge loss value for corresponding elements of two vectors namely 
`y_test` (5 x 1) and `y_pred` (5 x 1) and returns the mean of the loss values computed.

Note: `y_test` is the true test label and y_pred is the the predicted label.

In [ ]:
import numpy as np
def hinge_loss(y_pred,y_test):
    loss= np.mean([max(0, (1-x*y)) for x,y in zip(y_pred,y_test)])
    return loss

In [ ]:
import numpy as np
def hinge_loss(y_pred, y_test):
  loss = np.mean([max(0, (1-x*y)) for x,y in zip(y_pred, y_test)])

##SWI

In [ ]:
def loss(X, y, w, b, C):
  lin_comb = y * (X @ w +b)
  margin = w.T @ w/2
  hinge = C*np.sum(np.max([0, (1 - lin_comb)]))
  return margin + hinge

##Practice Programing Question 2
Write a function `'solve_eqn'` to obtain the weight vector (bias as its last element) of linear SVM model by accepting 
an array of support vectors `A` of shape (3 x 2) and their label vector b of shape (3 x 1). 
This function should return weight vector of shape 3 x 1.  

In [ ]:
import numpy as np

In [ ]:
import numpy as np
def solve_eqn(A,b):
    A = np.column_stack((A, np.ones(A.shape[0])))
    S = [[i @ j for j in A] for i in A]
    x = np.linalg.solve(S, b)
    w = np.zeros_like(x)
    for i in range(len(x)):
        w += x[i] * A[i]
    return w

In [ ]:
A = np.array([[1, 0], [3, 1], [3, -1]])
b = np.array([-1, 1, 1])
solve_eqn(A,b)

array([ 1.,  0., -2.])

In [ ]:
A = np.array([[8, 3], [-4, 7], [3, 4]])
b = np.array([1, -1, 1])

#print(solve_eqn(A, b))

In [ ]:
A = np.column_stack((A, np.ones(A.shape[0])))
A

array([[ 8.,  3.,  1.],
       [-4.,  7.,  1.],
       [ 3.,  4.,  1.]])

In [ ]:
S = [[i @ j for j in A] for i in A]
S

[[74.0, -10.0, 37.0], [-10.0, 66.0, 17.0], [37.0, 17.0, 26.0]]

In [ ]:
for i in A:
  #print(i)
  for j in A:
    #print(j)
    print(i, j, i*j)

[8. 3. 1.] [8. 3. 1.] [64.  9.  1.]
[8. 3. 1.] [-4.  7.  1.] [-32.  21.   1.]
[8. 3. 1.] [3. 4. 1.] [24. 12.  1.]
[-4.  7.  1.] [8. 3. 1.] [-32.  21.   1.]
[-4.  7.  1.] [-4.  7.  1.] [16. 49.  1.]
[-4.  7.  1.] [3. 4. 1.] [-12.  28.   1.]
[3. 4. 1.] [8. 3. 1.] [24. 12.  1.]
[3. 4. 1.] [-4.  7.  1.] [-12.  28.   1.]
[3. 4. 1.] [3. 4. 1.] [ 9. 16.  1.]


In [ ]:
x = np.linalg.solve(S, b)
x

array([-32.40625, -20.21875,  59.375  ])

In [ ]:
w = np.zeros_like(x)
w

array([0., 0., 0.])

In [ ]:
for i in range(len(x)):
        w += x[i] * A[i]
        print(w)

[-259.75     -99.71875  -18.90625]
[-178.875 -241.25   -39.125]
[-0.75 -3.75 20.25]


##Practice Programing Question 3
Write a class named `'fit_softsvm'` that implements soft margin SVM using GD. 

Write a separate function named `'support_vectors'` and return the support_vectors identified by the model. 

The inputs to the `'support_vectors'` function should be feature matrix X_train and label vector y_train.

Use the following parameters:

1.   learning rate=0.001
2.   C=500
3.   epochs=100

In [ ]:
import numpy as np
class fit_softSVM:
    def __init__(self, C=500):
       self.support_vectors= None
       self.C= C
       self.W = None
       self.b = None
       self.X = None
       self.y = None
       self.n=0
       self.d=0
      
    def __decision_function(self, X):
        return X.dot(self.w) + self.b
 
    def __cost(self, margin):
        return 0.5 * self.w.dot(self.w) + self.C * np.sum(np.maximum(0, 1 - margin))
 
    def __margin(self, X, y):
        return y * self.__decision_function(X)
 
    def fit(self, X, y, lr=0.001, epochs=100):
        self.n, self.d = X.shape
        self.w = np.random.randn(self.d)
        self.b = 0
        self.X = X
        self.y = y

        losses = []
        for _ in range(epochs):
            margin = self.__margin(X, y)
            loss = self.__cost(margin)
            losses.append(loss)
            
            misclassified_pts_idx = np.where(margin < 1)[0]
            d_w = self.w - self.C * y[misclassified_pts_idx].dot(X[misclassified_pts_idx])
            self.w = self.w - lr * d_w
            
            d_b = - self.C * np.sum(y[misclassified_pts_idx])
            self.b = self.b - lr * d_b
            
        self.support_vectors = np.where(self._margin <= 1)[0]
 
    def support_vectors(self, X_train, y_train):
        sp= fit(X_train, y_train)
        return sp

##Graded Programing Question 1
Write a function named` "hinge_loss" `that computes the hinge loss value for two vectors 
namely y_test (20 x 1) and y_pred (20 x 1) , and returns the mean of the loss values computed. 

Note: y_test is the true test label and y_pred is the the predicted label.

In [ ]:
import numpy as np
def hinge_loss(y_pred, y_test):
  loss = np.mean([max(0, (1 - x*y)) for x,y in zip(y_pred, y_test)])
  return loss

##Graded Programing Question 2
Write a function `'fit'` to compute gradient of the hinge loss function without regularization. 
This fit function should have the following input arguments-

```
X_train- feature matrix for training
Y_train - labels for training
X_test - features for testing
Y_test - labels for testing
n_iters - Number of iterations with default value 100
lr - learning rate with default value 0.1
```


The function should return the accuracy using the testing data.

In [ ]:
import numpy as np
def decision_function(X,w,b):
    return X.dot(w) + b
def cost(w,C, margin):
    return (1/2) * w.dot(w) + C * np.sum(np.maximum(0,1-margin))
def margin(X, y,w,b):
    return y * decision_function(X,w,b)
def fit(X_train,Y_train,X_test,Y_test,n_iters=100,lr=0.1):
        n, d = X_train.shape
        w = np.random.randn(d)
        b = 0
        C = 1
        
        X = X_train
        y = Y_train
        loss_array = []
        for _ in range(n_iters):
            Margin = margin(X,y,w,b)
            loss = cost(w,C,Margin)
            loss_array.append(loss)
            misclassified_pts_idx = np.where(Margin < 1)[0]
            d_w = w - C * y[misclassified_pts_idx].dot(X[misclassified_pts_idx])
            w = w - lr*d_w
            d_b =- C* np.sum(y[misclassified_pts_idx])
            b = b - lr* d_b
            
        support_vectors = np.where(margin(X,y,w,b) <= 1)[0]
        y_hat = np.sign(decision_function(X_test,w,b))
        accuracy = np.mean(Y_test == y_hat)
        return accuracy


##Graded Programing Question 3
Write a class named `'fit_softsvm'` that implements soft margin SVM using GD. 
Write a separate function named `'compute_accuracy'` and return the accuracy value 
using a `'pred_accuracy'` function which is defined inside the 'fit_svm' class. 

The inputs to the `'compute_accuracy'` function should be 
feature matrices `X_train, X_test` and label vectors `y_train, y_test`.

Use the following parametes:

```
1.   learning rate=0.01
2.   C=15
3.   epochs=100
```



In [ ]:
import numpy as np
class fit_softSVM:
    def __init__(self, C=15):
        self.support_vectors = None
        self.C = C
        self.b = None
      
    def __decision_function(self, X):
        return X.dot(self.w) + self.b
 
    def __cost(self, margin):
        return 0.5 * self.w.dot(self.w) + self.C * np.sum(np.maximum(0, 1 - margin))
 
    def __margin(self, X, y):
        return y * self.__decision_function(X)
 
    def fit(self, X, y, lr=0.01, epochs=100):
        n, d = X.shape
        self.w = np.random.randn(d)
        self.b = 0
        losses = []
        for _ in range(epochs):
            margin = self.__margin(X, y)
            loss = self.__cost(margin)
            losses.append(loss)
            
            misclassified_pts_idx = np.where(margin < 1)[0]
            d_w = self.w - self.C * y[misclassified_pts_idx].dot(X[misclassified_pts_idx])
            self.w = self.w - lr * d_w
            
            d_b = - self.C * np.sum(y[misclassified_pts_idx])
            self.b = self.b - lr * d_b
            
        self._support_vectors = np.where(margin <= 1)[0]
 
    def predict(self, X):
        return np.sign(self.__decision_function(X))
        
    def score(self, X, y):
        p = self.predict(X)
        return np.mean(y == P)
from sklearn.metrics import accuracy_score
def compute_accuracy(X_train, y_train, X_test,  y_test):
    svm = fit_softSVM(C=1)
    svm.fit(X_train, y_train)
    y_pred = svm.predict(X_test)
    return accuracy_score(y_test, y_pred)
    


#**WEEK_9**

##Practice Programing Question 1
Consider a regression problem with feature matrix X with size (100, 10) and label vector y with size (100, 1). We split this root node into two nodes 'node1' and 'node2' according to jth split variable and split value 's'.
Define a function `predict_node(X, y, j, s)` that takes X, y, split variable `j` and split value `s` as parameters and returns the tuple of predict values (mean value) at both the nodes.

X = ndarray of size (100, 10) with entries as float.

y = ndarray of size (100, 1) with entries as float.

j = int

s = float

In [ ]:
import numpy as np
def predict_node(X, y, j, s):
    node1 = [np.where(X[:,j]<=s)]
    node2 = [np.where(X[:,j]>s)]
    return (np.mean(y[node1]), np.mean(y[node2]))
    pass

##Practice Programing Question 2
Define a function `predict_class(y)` that takes the parameter
`y` which is a ndarray of actual outputs of all the samples in a particualar node and retruns the predict class for the same node.

Note: number of classes are 10 (0 to 9). 

If two classes have same number of samples, function should return the lower class. 

In [ ]:
import numpy as np
def predict_class(y):
  return np.bincount(y).argmax()

In [ ]:
y = [5, 8, 9, 5, 0 ,4, 0, 3, 9,2, 0, 4, 9, 2, 7, 7, 9, 8, 6, 9, 3, 7, 7, 4, 5, 9, 3, 6, 8, 0, 7]
 

In [ ]:
np.bincount(y)

array([4, 0, 2, 3, 3, 3, 2, 5, 3, 6])

In [ ]:
predict_class(y)

9

##Practice Programing Question 3
Define a function `misclassification_error(y)`  that takes the parameter `y` which is a ndarray of actual outputs of all the samples in a particular node and return the misclassification error of the same node.

In [ ]:
import numpy as np
import random
def misclassification_error(y):
  pred_class = np.bincount(y).argmax()
  mis_class  = np.where(y != pred_class)
  error = len(mis_class[0])/len(y)
  return error


##Graded Programing Question 1
Define a function `gini_index(dict)` having the 
following characteristics:

Input:
`dict` = dictionary that has classes as keys and 'number of samples in respective class' as values of a particular node.

Output:
Gini index of the same node. (A float value)

In [ ]:
import numpy as np
def gini_index(dict):
  n = sum(dict.values())
  p_sum = 0
  for value in duct.values():
    p_sum += (value/n) * (value/n)
  gini = 1- p_sum
  return gini


##Graded Programing Question 2
Define a function `entropy(dict)` having the 
following characteristics:

Input:
`dict` = dictionary that has classes as keys and 'number of samples in respective class' as values of a particular node.

Output:
Entropy of the same node. (A float value)

In [ ]:
import numpy as np
def entropy(dict):
  n = sum(dict.values())
  p = 0
  for value in dict.values():
    p += -(value/n)*np.log2(value/n)
  return p

##Graded Programing Question 3
Consider a regression problem using CART. If y is a ndarray of targets of the samples in a particular node, define a function `sseloss(y)` that returns the error associated with that node.

In [ ]:
import numpy as np
def sseloss(y):
  y_mean = np.mean(y)
  return np.sum((y - y_mean)**2, axis = 0)

#**WEEK_10**

##Practice Programing Question 1
Write a function `similarity(res,lambda_)` which takes residuals at a node as input and returns similarity score which can be used for `XGBoost regression.`

Input: A numpy array having residuals at a node.
          `lambda` is the regularization rate.

Output: Similarity score of the node.

`Note: Similarity Score= (Sum of residuals)2/(No. of residuals+lambda_)`

In [ ]:
import numpy as np
def similarity(res, lambda_):
  s = np.sum(res)
  d = len(res) + lambda_
  return (s**2)/d

##Practice Programing Question 2
Write a function `gradboost(model,X_train, y_train, X_test, boosting_rounds,learning_rate)` to implement Gradient boost algorithm.

Input:
model: model to be fitted

X_train: Training features

y_train: Training output labels

X_test: Test feature values

boosting_rounds: number of boosting rounds

learning_rate: learning rate used in the algorithm

Output:

y_hat_train: Prediction on training data after number of boosting rounds

y_hat_test:  Prediction on testing data after number of boosting rounds

In [ ]:
import numpy as np
def GradBoost(model, X_train, y_train, X_test, boosting_rounds, learning_rate: float = 0.1):
    #make a first guess of our training target variable using the mean of y_train
    y_hat_train = np.repeat(np.mean(y_train), len(y_train))

    #Initiate the test prediction with the mean of the training target variable.
    y_hat_test = np.repeat(np.mean(y_train), len(y_test))

    #Calculate the residuals
    residuals = y_train - y_hat_train

    #Iterate through the boosting rounds
    for i in range(boosting_rounds):
        #Fit the model to the residuals
        model = model.fit(X_train, residuals)

        #Increment the predicted training y with the pseudoresidulas * learning rate
        y_hat_train = y_hat_train + learning_rate * model.predict(X_train)

        #Increment the predicted test y as well
        y_hat_test = y_hat_test + learning_rate * model.predict(X_test)

        #Calculate the residuals for the next round
        residuals = y_train - y_hat_train

    return y_hat_train, y_hat_test

##Graded Programing Question 1
Write a function `reidual(y)` which takes a numpy array y as input and calculates residuals for base model(taking mean of the target values).

Input: numpy array y having all the target values.

Output: numpy array containing residuals.

In [ ]:
import numpy as np
def residuals(y):
  y_hat = np.repeat(np.mean(y), len(y))
  res = y - y_hat

##Graded Programing Question 2
Write a function `accuracy(y_true,y_pred)` which calculates accuracy of classification based on inputs `y_true` and `y_pred.`

Input:

`y_true`- vector of true output labels

`y_pred`-vector of predicted output labels.

Output:

 accuracy of classification

In [ ]:
def accuracy(y_true, y_pred):
  return np.sum(y_true == y_pred)/len(y_test)

##Graded Programing Question 3
Write a function `bag(X,y)`  for creating q bootstrap from original dataset.

`Input:` X is the feature matrix and y is the output label vector

`Output:` Bootstrap containing two numpy arrays containing feature values and corresponding target values.

In [ ]:
import numpy as np
np.random.seed(42)
def bag(X,y):
  n = X.shape[0]
  indices = np.random.choice(n, size = n, replace=True)
  return X[indices], y[indices]

#**WEEK_11**

##Practice Programing Question 1
Write a function `euclid(a,b)` to find Euclidean distance between vectors a and b.

Input: Vectors a and b

Return: Euclidean distance between vectors a and b

Note: both vectors are of shape (m, ), where m is some positive integer.

In [ ]:
import numpy as np
def euclid(a,b):
  return np.sqrt(np.sum((a-b)**2),axis = 0)

In [ ]:
import numpy as np
def euclid(a,b):
    E = np.linalg.norm(a - b)
    return E

##Graded Programing Question 1
Write a function to` centroid(a,b)` to find centroid of vectors a and b.

Input: a and b are numpy arrays of same shape.

Output: centroid of a and b as numpy array

In [ ]:
import numpy as np
def centroid(a, b):
  data = (a, b)
  c = np.mean(data, axis = 0)
  return c

In [ ]:
import numpy as np
def centroid(a, b):
  n = a.shape[0]
  c = []
  for i in range(n):
    c.append((a[i]+b[i])/2)
  return np.array(c)

##Graded Programing Question 2
Write a function `silhoutte(a,b)` to calculate silhoutte coefficient.

Input: `a` is the mean distance between the instances in the cluster and `b` is the mean distance between the instance and the instances in the next closest cluster.

Output: Silhoutte coefficient

In [ ]:
import numpy as np
def silhoutte(a,b):
  return (a*b)/max(a,b)