<a href="https://colab.research.google.com/github/samapatil1729/Machine-Learning-techniques/blob/main/OPPE1_Practice__MLT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

#WEEK_1
##PPA1
Write a function named vec_addition(u,v) which takes two vectors u and v as input and returns their vector addition.
 
  1. Inputs: u and v are two numerical numpy arrays. 
  2. Output: a vector representing sum of u and v, if they have consistent shapes, None otherwise.

In [ ]:
def vec_addition(u,v):
  if u.shape==v.shape:
    return u+v
  else:
      return None

In [ ]:
u=np.array([1,2,3])
v=np.array([4,5,6])
vec_addition(u,v)

array([5, 7, 9])

In [ ]:
x=np.array([1,2,3])
y=np.array([5,6])
vec_addition(x,y)

##PPA2
write a function named scalar_multiply(u,k) which takes a vector u and a scalar k as input and returns k times u as output
 
  1. Inputs: A vector u and a scalar k
  2. Output: Returns a vector which is k times u

In [ ]:
def scalar_multiply(u,k):
  return u*k

In [ ]:
x=np.array([1,2,3])
scalar_multiply(u,3)

array([3, 6, 9])

##PPA3
Write a function hadamard(u,v) which takes two vectors u and v as input and returns hadamard product of u and v.
Hdamard product is obtained via multiplying two matrices/vectors elementwise.
 
  1. Inputs: Two vectors u and v
  2. Output: Hadamard product of u and v if the dimensions of u and v are consistent, otherwise None

In [ ]:
def hadmard(u,v):
  if u.shape==v.shape:
    return u*v
  else:
    return None

In [ ]:
u=np.array([1,2,3])
v=np.array([4,5,6])
hadmard(u,v)

array([ 4, 10, 18])

##GrPA 1
Write a function dot_product(u,v) which take two vectors u and v as input and returns inner product of u and v as output
 
  1. Inputs: vectors u and v 
  2. Output: dot product of u and v if u and v have consistent dimension otherwise None

In [ ]:
def dot_product(u,v):
  if u.shape==v.shape:
    return u @ v    #np.dot(u,v)
  else:
    return None

In [ ]:
u=np.array([1,2,3])
v=np.array([4,5,6])
dot_product(u,v)

32

##GrPA 2
Write a function add_constant(u,k) which adds a constant k to each element of u
 
  1. Inputs: u is a vector,k is a scalar 
  2. Output: C is a vector

In [ ]:
def add_constant(u,k):
  return k+u

In [ ]:
u=np.array([1,2,3])
add_constant(u,7)

array([ 8,  9, 10])

##GrPA 3
Write a function add_matrix(X,Y) to add two matrices X and Y.
 
  1. Inputs: X is a matrix, Y is a matrix 
  2. Output: Z is a matrix representing (X+Y) if X and Y have consistent dimension otherwise None

In [ ]:
def add_matrix(X,Y):
  if X.shape==Y.shape:
    return X+Y
  else:
    return None

In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
add_matrix(A,B)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

#**WEEK_2**
##PPA 1
Write a function add_one(X) to include first column with all elements 1 in X.
 
  1. Inputs: A matrix X
  2. Output: updated matrix with a column having elements 1 added as first column to X.

In [ ]:
def add_one(X):
  n = len(X)
  return np.c_[np.ones(n), X]

def add_zeros(X):
  n = len(X)
  return np.c_[np.zeros(n), X]


In [ ]:
A=[[1,2,3],[4,5,6],[7,8,9]]
add_one(A)

array([[1., 1., 2., 3.],
       [1., 4., 5., 6.],
       [1., 7., 8., 9.]])

In [ ]:
add_zeros(A)

array([[0., 1., 2., 3.],
       [0., 4., 5., 6.],
       [0., 7., 8., 9.]])

##To include first column with all elements 'a' in X.

In [ ]:
def add_number(X,a):
  n = len(X)
  return np.c_[a+np.zeros(n), X]

In [ ]:
A=[[1,2,3],[4,5,6],[7,8,9]]
add_number(A,3)

array([[3., 1., 2., 3.],
       [3., 4., 5., 6.],
       [3., 7., 8., 9.]])

#PPA 2
Write a function multiply(X,w) to Multiply feature matrix(X) and weight vector(w) after addition of dummy feature to feature matrix.

Inputs: Feature matrix X and weight vector w
Output: Product of X and w after adding dummy feature to feature matrix X. If the dimensions are not consistent return None.

In [ ]:
def multiply(X,w):  
  A = np.c_[np.ones(len(X)),X]
  if (A.shape[-1])==w.shape[0]:
    return (A)@w
  else:
    return None

In [ ]:
A=[[1,2,3],[4,5,6],[7,8,9]]
w = np.array([1,2,3,4])
multiply(A,w)

array([21., 48., 75.])

##PPA 3
Write a function loss(X,w,y) which takes feature matrix(X), weight vector(w) and output label vector(y) and returns sum squared loss while implementing regression model.(Note: Do necessary preprocessing of X)
 
  1. Inputs: Feature matrix X and weight vector w and output label vector y
  2. Output: sum squared loss if dimensions of inputs are consistent, otherwise None

In [ ]:
def loss(X,w,y):
  A = np.c_[np.ones(len(X)),X]
  if A.shape[-1]==w.shape[0]:
    y_pred = A@w
    return np.sum((y_pred-y)**2)*0.5
  else:
    return None

#OR

In [ ]:
def loss(X,w,y):
  N = len(X)
  A=np.c_[ np.ones(N), X]
  if A.shape[-1]!=w.shape[0]:
    return None
  e = (A @ w)-y
  return  (1/2) * (np.transpose(e) @ e)

##GrPA 1
Write a function compatibility(X,w) to find whether X and w can be multiplied or not.
 
  1. Inputs: Feature matrix X and weight vector w,
  2. Output: return "C" if X and w can be multiplied otherwise None.

In [ ]:
def compatibility(X,w):
  A = np.c_[np.ones(len(X)),X]
  if A.shape[-1]==w.shape[0]:
    return "C"
  return None

##GrPA 2
Write a function gradient(X,w,y) to calculate gradient of loss function w.r.t weight vector given that X is the feature matrix, w is the weight vector and y is the output vector.
(Note: do necessary preprocessing of X)
 
  1. Inputs: Feature matrix X, weight vector w, and output label vector y.
  2. Output: gradient if dimesnsions of inputs are consistent, otherwise None

Note: Preprocess X, if necessary.

In [ ]:
def gradient(X,w,y):
  A = np.c_(np.ones(len(X)),X)
  if A.shape[-1]!=w.shape[0]:
    return None
  y_pred = A@w-y
  return np.transpose(A)@ y_pred


##GrPA 3
Write a function weight_update(X,w,y,lr) to get updated weight after one iteration of gradient descent given that X is the feature matrix, w is the weight vector and y is the output label vector.
(Note: Do necessary preprocessing of X)
 
  1. Inputs: Feature matrix X, weight vector w, output label vector y and learning rate lr
  2. Output: weight updates after gradient calculation if dimensions of inputs are consistent, otherwise None

In [ ]:
def weight_update(X,w,y,lr):
  A = np.c_[np.ones(len(x)),X]
  if A.shape[-1]!=w.shape[0]:
    return None
  y_pred = (A@w)-y
  Grd = np.transpose(A) @ y_pred
  return w - lr*Grd

##Practice Assignment

In [ ]:
def gen_data(n):
    #obtain y=6+5x+noise
    w0=6
    w1=5
    X=10*np.random.rand(2*n,)
    y=w0+w1*X+np.random.randn(2*n,)
    return X,y

X,y=gen_data(250)

#**WEEK_3**
##PPA 1

Consider input feature vector X. The shape of X is fixed (1 x 3) and the degree of the polynomial is a random number (between 2 to 10).

Write a function named 'polynomial_transform' which takes the feature vector and degree of the polynomial as inputs and returns the transformed polynomial feature as output as a numpy array.

In [ ]:
import random
import itertools
import functools

def polynomial_transform(X, degree):
  if X.ndim==1:
    X = X[:,None]
  X_t = X.transpose()
  features = [np.ones(len(X))]
  for degree in range(1, degree+1):
    for items in itertools.combination_with_replacement(X_t, degree):
      features.append(functools.reduce(lambda x, y: x * y, items))
  return np.asarray(features).transpose()

##PPA 2
Consider input feature matrix X, label y and weight w. The size of X, y and w are fixed to (10 x 3), (10 x 1) and (4 x 1).

Write a loss function named 'ridge_loss' to compute ridge regression loss. This function should take the feature matrix (X), label vector (y), weight vector(w) and regularization rate (l) as inputs and return the loss value as output. Note: Add a dummy feature to X.

In [ ]:
import random
def ridge_loss(X, y, w,l):
  A = np.c_[np.ones(len(X)),X]  # A= np.column_stack((np.ones(X.shape[0]), X))
  e = A@w-y
  return (0.5*(e.T@e)+1/2*(w.T@w))


##GrPA 1
Government of India is taking several steps to ensure that we are well prepared to face the challenges and threats posed by COVID-19. With active support of citizens of India, Goverment have been able to mitigate the spread of the virus so far.

One of the most important factors in the fight with the virus is to vaccinate maximum people and enable them to take precautions as per the advisories being issued by different Ministries.

Total 50 month's data and total vaccination in each month is given.

After initial data exploration you got to know that the given data don't follow linear model.

Now You have to define function "model_error" which will fit the given data on linear regression model with appropriate degree and return RMSE error.

In [ ]:
import numpy as np
import random
import itertools
import functools

def polynomial_transformation(X,degree):
  if X.ndim==1:
    X=X[:,None]
  X_t = X.transpose()
  feature = np.c_[np.ones(len(X))]
  for degrees in range(1,degree+1):
    for items in itertools.combination_with_replacement(X_t,degree):
      feature.append(functools.reduce(lambda x,y: x*y, items))
  return np.asarray(feature).transpose()
  
def model_error(X, y,degree):
    X = polynomial_transform(X, degree)
    w = np.linalg.pinv(X) @ y
    y_pred = X @ w
    e = y - y_pred
    return np.sqrt(2/X.shape[0] * 0.5 *(e.T @ e))

#OR

In [ ]:
import numpy as np
import random
def model_error(X, y,degree):
 
  from sklearn.linear_model import LinearRegression
  transformed_features = polynomial_transform(X, degree)
  polyreg = LinearRegression()
  w_nonlin = polyreg.fit(transformed_features, y)
  y_pred=w_nonlin.predict(polynomial_transform(X,degree))
  training_error=y_pred-y
  train_loss = (1/2) * (np.transpose(training_error) @ training_error) 
  rmse = np.sqrt((2/X.shape[0])*train_loss)
  return rmse

##GrPA 2
Consider input feature matrix X having size of (20 x 3).

You do not have to generate these values.

Write a function named additional_vector which will creates a list of size 20 having 1 at even place and zero at odd place.(e.g-[0,1,0,1]) Then later it returns new updated matrix by stacking X and new vector columnwise.

In [ ]:
import numpy as np
import random
def additional_vector(X):
  a = [0,1]*10
  return np.c_[X,a]

In [ ]:
X = np.random.randn(60).reshape(20,3)

In [ ]:
X
additional_vector(X)

array([[ 0.85526914,  0.79001823,  0.42458493,  0.        ],
       [ 0.23576942,  1.30157352,  0.57932086,  1.        ],
       [ 0.07969082,  0.09328467,  0.64027615,  0.        ],
       [ 0.88533312, -0.74128539, -2.07150742,  1.        ],
       [-0.02532683, -0.21787832, -0.1528021 ,  0.        ],
       [-0.46816304,  0.7242731 , -0.65808879,  1.        ],
       [-0.0323559 , -0.15812082,  0.9908026 ,  0.        ],
       [ 0.20320915, -0.28450078,  1.56346822,  1.        ],
       [-0.69235324, -0.9461751 ,  2.08100271,  0.        ],
       [-0.67839151,  0.12134176, -0.14565432,  1.        ],
       [-0.37344173, -0.13600785,  0.89879905,  0.        ],
       [ 1.03274839,  1.47951702, -1.97264618,  1.        ],
       [-0.76826694, -1.59199163, -0.24853319,  0.        ],
       [ 1.27708674,  0.24818597, -0.13695513,  1.        ],
       [-0.89459275,  1.69366994, -0.04433117,  0.        ],
       [ 1.61651299,  0.18027494, -0.64087679,  1.        ],
       [ 0.34122252,  0.

##GrPA 3
Consider input feature matrix X, label y and weight w. The size of X, y and w are fixed to (20 x 3), (20 x 1) and (3 x 1) respectively and these will have random values.

You do not have to generate these values.

Write a function named mean_abs to compute mean absolute error. This function should take the feature matrix, label vector, weight vector as inputs and return the mean absolute value as output.

In [ ]:
import numpy as np
import random
def mean_abs(X,y,w):
  y_pred = X @ w
  return 0.5*np.sum(np.abs(y - y_pred))

##OR

In [ ]:
import numpy as np
import random
def mean_abs(X,y,w):
  predicted_y= X@w
  error= y-predicted_y
  abs_error=abs(error)
  mean_matrix=(1/len(X))* (abs_error)
  mean_sum=np.sum(np.sum(mean_matrix, axis=1))
  return mean_sum

#WEEK_4
##PPA 1
Define a function `ConfusionMatrix(y,y_hat)` for binary classification and return a matrix in the following format: `[[TN,FP],[FN,TP]]`
 
  1. Inputs:  y: 1 x n, y_hat: 1 x n 
  2. Output: 2D numpy array. <br>

In [ ]:
import numpy as np
def ConfusionMatrix(y,y_hat):
  TN = np.where((y==0) & (y_hat==0),1,0).sum()
  FP = np.where((y==0) & (y_hat==1),1,0).sum()
  FN = np.where((y==1) & (y_hat==0),1,0).sum()
  TP = np.where((y==1) & (y_hat==1),1,0).sum()
  return np.array([[TN,FP],[FN,TP]])

##PPA 2
Define a function `is_binary(y)` to check whether the label vector y belongs to binary classification or not. If the labels are binary then return True (i.e., state=True (Boolean))  else return False (i.e., state = False).

All elements in y are integer numbers (not the datatype). 

In [ ]:
import numpy as np
def is_binary(y):
    if len(np.unique(y)) == 2:
        return True
    return False

##PPA 3
Write a function `percep_loss(X,w,y,i)` to compute the perceptron loss for all 
the sample in $X$ and return the loss for individual samples in a vector.

In [ ]:
import numpy as np
def percep_loss(x,w,y):
  samplewise_loss = None
  z = x @ w
  y_predict = np.where (z >= 0, 1, -1)
  samplewise_loss = np.maximum(-1 * y_predict * y, np.zeros(y.shape[0]))
  return samplewise_loss

##GrPA 1
Write a function OneHotEncode(y) to convert integer labels to one hot-encoded labels.

In [ ]:
b = np.array([1,2,-3])
b

array([ 1,  2, -3])

In [ ]:
np.sum(np.abs(b))

6

In [ ]:
import numpy as np
def OneHotEncode(y):
  n = np.max(y) + 1
  return np.eye(n)[y]

Implement the perceptron weight update rule. Name the function as `update(x,w,y,epoch)` to update the weight vector over n epochs and returns the history of the weight updates as a matrix (or a vector if there is only one feature). 
* The row represents the weight values at ith epoch. The zeroth row represents the weight value at epoch zero (that is the one directly passed an argument to the function).

[Note: Keep learning rate alpha as 1.0]

In [ ]:
import numpy as np
def update(x,w,y,epochs):
    history = []
    wi = np.zeros(x.shape[1])
    history.append(wi)
    wi = w
    for i in range(epochs):
        for xi, target in zip(x,y):
            y_pred = np.where((xi@wi)>= 0, 1, -1)
            wi = wi + (target - y_pred)*xi
        history.append(wi)
    return history

Implement a function with a name `is_linearly_separable()` that takes in data matrix with a dummy feature (X) and label vector (y). The function returns True if the datapoints are linearly separable, False otherwise.

Note: The maximum number of epochs should not exceed 10.


In [ ]:
import numpy as np
def is_linearly_separable(X,y):
  error = []
  w = np.zeros(X.shape[1])
  for i in range(10):
      err = 0
      for xi, target in zip(X, y):
          y_pred = np.where((xi@w)>=0,1,-1)
          w += (target - y_pred)*xi
          err +=max((-1*(xi@w)*target), 0)
      error.append(err)
      if error[-1] == 0:
          state = True
      else:
          state = False
  return state

You are provided with an input feature matrix X, label y and weight w. 
The size of X, y and w are fixed to (100 x 5), (100 x 1) and (6 x 1). 
You have to add a dummy feature to X. 

Write a loss function named 'loss' to compute ridge and lasso regression losses for the given data. 
This function should take the feature matrix, label vector, weight vector and regularization rate as inputs and 
return the minimum of two loss values as output.

In [ ]:
import numpy as np
import random
def loss(X, y, w, lr):
  ones_vector = np.ones(X.shape[0])
  X = np.column_stack((ones_vector, X))
  ridgeloss = (1/2) * (np.transpose(X@w-y))@(X@w-y) + (lr/2)* (np.transpose(w) @ w)
  lassoloss = (1/2) * (np.transpose(X@w-y))@(X@w-y) + (lr/2)* np.sum(abs(w))
  if ridgeloss < lassoloss:
    out = ridgeloss
  else:
    out = lassoloss
  return out

Researchers Cook and Weisberg (1999) measured and recorded the age (in years) and length (in mm)  of some 
randomly sampled 'Bluegills' fishes from Lake Mary in Minnesota. 
They were primarily interested in learning how the length of a bluegill fish is related to its age. 
Their observation by plotting the length vs age suggests that there is positive trend in the data, 
however, it doesn't appear to be quite linear. It appears as if there is some kind of nonlinear relationship. 

- You are provided with x (age of the fish), y (length of the fish) and test (age for which length is unknown). 
x and y are numpy arrays of shape 78 x 1 and test is a numpy array of size 1 X 1. 
- You have to apply second degree polynomial transformation on x.
- Using only numpy, implement a linear regression model by stochastic gradient descent procedure on the transformed data with 
300 iterations, initial weights as zero and learning rate as 0.001.

What is the length of a test bluegill fish that is randomly selected based on its age? 
- Define a function named 'output' which accepts x, y, test as inputs and returns new predicted length (float) as output. 

In [ ]:
import numpy as np
import itertools
import functools
def polynomial_transform(x, degree):
  if x.ndim == 1:
    x = x[:, None]
  x_t = x.transpose()
  features = [np.ones(len(x))]
  for degree in range(1, degree + 1):
    for items in itertools.combinations_with_replacement(x_t, degree):
      features.append(functools.reduce(lambda x, y: x * y, items))
  return np.asarray(features).transpose()